- hosts: all
  become: yes
  tasks:
    - name: apt
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes

    - name: get vi
      apt: state=latest name=vim
      register: aptout

    - debug:
        var: aptout
